runtime: go113

main: ./cmd/


env_variables:
  # Replace INSTANCE_CONNECTION_NAME with the value obtained when configuring your
  # Cloud SQL instance, available from the Google Cloud Console or from the Cloud SDK.
  # For Cloud SQL 2nd generation instances, this should be in the form of "project:region:instance".
  # INSTANCE_CONNECTION_NAME: <project>:<region>:<instance>
  INSTANCE_CONNECTION_NAME: sushita:us-central1:sushita-server
  DB_USER: sushita-user
  DB_PASS: pass
  DB_NAME: sushita_server
handlers:
- url: /.*
  script: auto

