version: '3'

services:
    app:
        build: 
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        container_name: golang-container
        environment:
            - "GOPATH=/go"
        tty: true
        volumes:
            - ./:/go/src/github.com/mox692/sushita_serve
        depends_on:
            - mysql
    mysql:
        image: mysql:latest
        container_name: mysql-container
        ports:
            - 3306:3306
        environment:
          MYSQL_DATABASE: golang-test-database
          MYSQL_USER: golang-test-user
          MYSQL_PASSWORD: golang-test-pass
        volumes: 
            - ./db/init:/docker-entrypoint-initdb.d
            - go-data:/var/lib/mysql

volumes:
  go-data:
    driver: local